site_name: Easy Classical ML & DL
site_url: https://rameshaditya-me.github.io/Easy-Classical-ML-DL/
repo_url: https://github.com/rameshaditya-me/Easy-Classical-ML-DL
repo_name: rameshaditya-me/Easy-Classical-ML-DL

docs_dir: src

theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - tables

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Notebooks:
      - Linear Regression: notebooks/linear-regression/linear-regression.md
      - Regularized Regression: notebooks/regularized-regression/regression_regularized.md
      - Logistic Regression: notebooks/logistic-regression/logistic_regression.md
